include: [".well-known"]

remote_theme: remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

title: [BitCal]
description: [Your Nostr buddy ensuring you do not miss any Bitcoin holidays or events]
